### ISSUE TITLE
empty repo (VERY BIG BUG/ISSUE PLEASE FIX)

### ISSUE THREAD

**Issue by Cartrigger** [PlazmaMC/Plazma#1]
😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢

**Comment by XionioXMaster** [comment]
Bruh
