### ISSUE TITLE
Backport to 1.16 and below

### ISSUE THREAD

**Issue by MrRagtime** [PlazmaMC/Plazma#49]
Hello, I was just wondering if a backport was possible for 1.16 and maybe 1.7
If not it is cool.

**Comment by IPECTER** [comment]
I don't think Plazma''s approach effective in lower versions than 1.18
Take a look at [Purpur(Purpur-Airplane) 1.16.5](https://purpurmc.org/downloads/1.16.5), which was considered the best performance at the time. maybe [SportPaper 1.8](https://github.com/Electroid/SportPaper) is good for 1.8.

**Comment by MrRagtime** [comment]
ah alright and I'll take a look at that thx
