### ISSUE TITLE
35555535353535353 tps optimization

### ISSUE THREAD

**Issue by Delyfsss** [PlazmaMC/Plazma#50]
https://github.com/KaiijuMC/Kaiiju/blob/ver/1.20.1/patches/server/0044-Async-path-processing.patch

**Comment by IPECTER** [comment]
...?

**Comment by IPECTER** [comment]
@Delyfsss WIP
ETA 12 HOURS

**Comment by IPECTER** [comment]
Check Latest
(But default value is disabled. you need to change config)
